// Handoff orchestration (spec §7). Turns an agent `done` into a review-ready,
// human-pinged MR via a FIXED ordered sequence over the M2 adapter surface:
//
//   proof comment (issue) → proof comment (MR) → assign reviewer → un-draft → label in-review
//
// The ordering is the contract (§7): the human is pinged (assignMR) ONLY after the
// proof is posted, so review-ready means everything is ready. Proof is generated by
// the caller and passed in (frozen HandoffInput.proof); `proofAndHandoff` composes
// generation + handoff and preserves "proof generated before reviewer assigned".
//
// Re-entrant on crash recovery (§0.4): each mutating step is guarded by an OBSERVABLE
// forge predicate read from a fresh snapshot, so a re-run skips already-applied steps
// — no double-comment, no double-assign, no local persistence. The DONE_SENTINEL
// embedded in the proof comment is the legible "proof already posted" marker.

import {
  DONE_SENTINEL,
  type HandoffInput,
  type IssueSnapshot,
  type ProofInput,
  type ProofResult,
} from '../contracts/index.js';
import { type PlaywrightTuning, generateProofs } from '../proof/strategies.js';
import { lifecycleMove } from '../reconciler/transitions.js';

/** Fold N proof results into one comment: header is all-must-pass (ok = AND), each
 *  strategy gets its own labelled section. A single strategy renders flat (no label),
 *  preserving the original one-proof comment shape. */
function proofCommentBody(proofs: ProofResult[]): string {
  const allOk = proofs.every((p) => p.ok);
  const header = allOk ? '### ✅ Proof' : '### ⚠️ Proof (failed — review with caution)';
  const body =
    proofs.length === 1
      ? (proofs[0]?.summary ?? '')
      : proofs.map((p) => `#### ${p.ok ? '✅' : '❌'} ${p.kind}\n\n${p.summary}`).join('\n\n');
  return `${header}\n\n${body}\n\n${DONE_SENTINEL}`;
}

/** Idempotency marker for the fallback reviewer @-mention (handoff step 3, #6). */
const REVIEW_PING_SENTINEL = '<!-- maestro:reviewer-ping -->';

function reviewPingBody(ticketCreator: string): string {
  return (
    `@${ticketCreator} this is ready for your review. I couldn't assign you to the MR ` +
    `(you may not have access to this repo), so flagging it here instead.\n\n${REVIEW_PING_SENTINEL}`
  );
}

/**
 * Execute the §7 handoff sequence idempotently. Reads current forge state once, then
 * runs each step only if its predicate is unsatisfied. Matches the frozen HandoffFn.
 */
export async function handoff(input: HandoffInput): Promise<void> {
  const { adapter, repo, issueIid, mrIid, ticketCreator, settings, proof } = input;
  const snap = await adapter.getSnapshot(repo, issueIid);
  const mr = snap.mr;

  // 1+2. Proof comments (issue then MR) — guarded by the sentinel on the issue.
  const proofPosted = snap.recentComments.some((c) => c.body.includes(DONE_SENTINEL));
  if (!proofPosted) {
    const body = proofCommentBody(proof);
    await adapter.commentIssue(repo, issueIid, body);
    await adapter.commentMR(repo, mrIid, body);
  }

  // 3. Assign the ticket creator (the reviewer) — guarded by current assignees.
  const assigned = (mr?.assignees ?? []).some((a) => a.username === ticketCreator);
  if (!assigned) {
    await adapter.assignMR(repo, mrIid, ticketCreator);
    // GitHub/GitLab SILENTLY DROP an un-assignable user (a non-collaborator ticket author on a
    // public repo, or a misconfigured bot_user) — assignMR doesn't throw, so the guard above
    // can't see the no-op and the human would never be pinged. Re-read; if the assignee didn't
    // land, @-mention them instead (a mention notifies anyone, access or not). Idempotent via a
    // sentinel so crash-recovery re-runs don't double-ping (#6).
    const after = await adapter.getSnapshot(repo, issueIid);
    const landed = (after.mr?.assignees ?? []).some((a) => a.username === ticketCreator);
    const alreadyPinged = snap.recentComments.some((c) => c.body.includes(REVIEW_PING_SENTINEL));
    if (!landed && !alreadyPinged) {
      await adapter.commentIssue(repo, issueIid, reviewPingBody(ticketCreator));
    }
  }

  // 4. Un-draft — guarded by draft state.
  if (mr?.isDraft !== false) {
    await adapter.setDraft(repo, mrIid, false);
  }

  // 5. Label in-review (terminal step) — guarded by label presence.
  const labeled = snap.issue.labels.includes(settings.labels.inReview);
  if (!labeled) {
    const m = lifecycleMove('enter-review', settings.labels);
    await adapter.setIssueLabels(repo, issueIid, m.set, m.unset);
  }
}

/** Is the handoff fully complete per forge state? (Used by M5 to short-circuit.) */
export function isHandoffComplete(
  input: Pick<HandoffInput, 'settings'>,
  snapshot: IssueSnapshot,
): boolean {
  const mr = snapshot.mr;
  const proofPosted = snapshot.recentComments.some((c) => c.body.includes(DONE_SENTINEL));
  const labeled = snapshot.issue.labels.includes(input.settings.labels.inReview);
  return proofPosted && mr?.isDraft === false && labeled;
}

export interface ProofAndHandoffInput extends Omit<HandoffInput, 'proof'> {
  proofInput: Omit<ProofInput, 'workflowProof' | 'git'> & {
    strategies: ProofInput['workflowProof'][];
    git?: { target: string };
  };
  playwrightTuning?: PlaywrightTuning;
}

/**
 * Compose generation + handoff: run every configured proof strategy FIRST, then run
 * the ordered handoff with the folded results. This is the unit M5 calls on
 * `AgentResult.status === 'done'`. Proof generation completing before any adapter
 * mutation preserves the §7 proof-before-assign guarantee end-to-end.
 */
/**
 * Proof WITHOUT the handoff (#29 P3): run every configured strategy and post the folded
 * proof comment (with DONE_SENTINEL), leaving the MR draft and the reviewer unassigned —
 * the internal review gate decides when the human handoff runs. Same §7 guarantee:
 * proof generation completes before the one adapter mutation (the comment).
 */
export async function proofAndComment(input: ProofAndHandoffInput): Promise<ProofResult[]> {
  const gitTarget: { target: string } = input.proofInput.git ?? {
    target: input.settings.git.target,
  };
  const { strategies, git: _git, ...base } = input.proofInput;
  const proof = await generateProofs(
    { ...base, git: gitTarget },
    strategies,
    input.playwrightTuning,
  );
  await input.adapter.commentIssue(input.repo, input.issueIid, proofCommentBody(proof));
  return proof;
}

export async function proofAndHandoff(input: ProofAndHandoffInput): Promise<ProofResult[]> {
  const gitTarget: { target: string } = input.proofInput.git ?? {
    target: input.settings.git.target,
  };
  const { strategies, git: _git, ...base } = input.proofInput;
  const proof = await generateProofs(
    { ...base, git: gitTarget },
    strategies,
    input.playwrightTuning,
  );
  await handoff({
    repo: input.repo,
    issueIid: input.issueIid,
    mrIid: input.mrIid,
    ticketCreator: input.ticketCreator,
    settings: input.settings,
    adapter: input.adapter,
    proof,
  });
  return proof;
}
