// Handoff orchestration (spec §7). Turns an agent `done` into a review-ready,
// human-pinged MR via a FIXED ordered sequence over the M2 adapter surface:
//
//   proof comment (issue) → proof comment (MR) → request review → ready comment → un-draft → label in-review
//
// The ordering is the contract (§7): the human is pinged (the ready comment) ONLY after the
// proof is posted, so review-ready means everything is ready. Proof is generated by
// the caller and passed in (frozen HandoffInput.proof); `proofAndHandoff` composes
// generation + handoff and preserves "proof generated before the reviewer is pinged".
//
// Re-entrant on crash recovery (§0.4): each mutating step is guarded by an OBSERVABLE
// forge predicate read from a fresh snapshot, so a re-run skips already-applied steps
// — no double-comment, no double-assign, no local persistence. The DONE_SENTINEL
// embedded in the proof comment is the legible "proof already posted" marker.

import {
  DONE_SENTINEL,
  type HandoffInput,
  type IssueSnapshot,
  type ProofInput,
  type ProofResult,
} from '../contracts/index.js';
import { type PlaywrightTuning, generateProofs } from '../proof/strategies.js';
import { lifecycleMove } from '../reconciler/transitions.js';

/** Fold N proof results into one comment: header is all-must-pass (ok = AND), each
 *  strategy gets its own labelled section. A single strategy renders flat (no label),
 *  preserving the original one-proof comment shape. */
function proofCommentBody(proofs: ProofResult[]): string {
  const allOk = proofs.every((p) => p.ok);
  const header = allOk ? '### ✅ Proof' : '### ⚠️ Proof (failed — review with caution)';
  const body =
    proofs.length === 1
      ? (proofs[0]?.summary ?? '')
      : proofs.map((p) => `#### ${p.ok ? '✅' : '❌'} ${p.kind}\n\n${p.summary}`).join('\n\n');
  return `${header}\n\n${body}\n\n${DONE_SENTINEL}`;
}

/** Idempotency marker for the ready-for-review comment (handoff step 4, #115). */
const READY_SENTINEL = '<!-- maestro:ready-for-review -->';

/** The handoff ping: a single comment that always @-mentions the ticket creator, so it
 *  notifies whether or not the forge review request landed (a non-collaborator creator, or a
 *  GitHub 422 on a shared bot account). Carries the MR link and the three response channels. */
function readyBody(ticketCreator: string, mrUrl: string | undefined, botUser: string): string {
  const link = mrUrl ? ` (${mrUrl})` : '';
  const channels = [
    'To respond, pick whichever is natural:',
    '- **Approve** or **request changes** on the MR, or',
    `- start a comment with \`/maestro <feedback>\` — or \`@${botUser} <feedback>\` from your own account — on the MR or this issue.`,
  ].join('\n');
  return `@${ticketCreator} this is ready for your review${link}. Proof is posted above.\n\n${channels}\n\n${READY_SENTINEL}`;
}

/**
 * Execute the §7 handoff sequence idempotently. Reads current forge state once, then
 * runs each step only if its predicate is unsatisfied. Matches the frozen HandoffFn.
 */
export async function handoff(input: HandoffInput): Promise<void> {
  const { adapter, repo, issueIid, mrIid, ticketCreator, settings, proof } = input;
  const snap = await adapter.getSnapshot(repo, issueIid);
  const mr = snap.mr;

  // 1+2. Proof comments (issue then MR) — guarded by the sentinel on the issue.
  const proofPosted = snap.recentComments.some((c) => c.body.includes(DONE_SENTINEL));
  if (!proofPosted) {
    const body = proofCommentBody(proof);
    await adapter.commentIssue(repo, issueIid, body);
    await adapter.commentMR(repo, mrIid, body);
  }

  // 3. Request review from the ticket creator — guarded by the current reviewer list.
  // requestReview is a no-op when the forge refuses (a non-collaborator creator, or the
  // GitHub author-422 on a shared bot account); the ready comment below is what guarantees
  // the human is notified, so a dropped request is harmless.
  const requested = (mr?.reviewers ?? []).some((r) => r.username === ticketCreator);
  if (!requested) {
    await adapter.requestReview(repo, mrIid, ticketCreator);
  }

  // 4. Ready-for-review comment (the ping, §7) — always @-mentions, so it notifies regardless
  // of whether step 3 landed. Guarded by its own sentinel so crash-recovery re-runs don't
  // double-ping (#115).
  const pinged = snap.recentComments.some((c) => c.body.includes(READY_SENTINEL));
  if (!pinged) {
    await adapter.commentIssue(
      repo,
      issueIid,
      readyBody(ticketCreator, mr?.webUrl, settings.botUser),
    );
  }

  // 5. Un-draft — guarded by draft state.
  if (mr?.isDraft !== false) {
    await adapter.setDraft(repo, mrIid, false);
  }

  // 6. Label in-review (terminal step) — guarded by label presence.
  const labeled = snap.issue.labels.includes(settings.labels.inReview);
  if (!labeled) {
    const m = lifecycleMove('enter-review', settings.labels);
    await adapter.setIssueLabels(repo, issueIid, m.set, m.unset);
  }
}

/** Is the handoff fully complete per forge state? (Used by M5 to short-circuit.) */
export function isHandoffComplete(
  input: Pick<HandoffInput, 'settings'>,
  snapshot: IssueSnapshot,
): boolean {
  const mr = snapshot.mr;
  const proofPosted = snapshot.recentComments.some((c) => c.body.includes(DONE_SENTINEL));
  const labeled = snapshot.issue.labels.includes(input.settings.labels.inReview);
  return proofPosted && mr?.isDraft === false && labeled;
}

export interface ProofAndHandoffInput extends Omit<HandoffInput, 'proof'> {
  proofInput: Omit<ProofInput, 'workflowProof' | 'git'> & {
    strategies: ProofInput['workflowProof'][];
    git?: { target: string };
  };
  playwrightTuning?: PlaywrightTuning;
}

/**
 * Compose generation + handoff: run every configured proof strategy FIRST, then run
 * the ordered handoff with the folded results. This is the unit M5 calls on
 * `AgentResult.status === 'done'`. Proof generation completing before any adapter
 * mutation preserves the §7 proof-before-assign guarantee end-to-end.
 */
/**
 * Proof WITHOUT the handoff (#29 P3): run every configured strategy and post the folded
 * proof comment (with DONE_SENTINEL), leaving the MR draft and no review requested —
 * the internal review gate decides when the human handoff runs. Same §7 guarantee:
 * proof generation completes before the one adapter mutation (the comment).
 */
export async function proofAndComment(input: ProofAndHandoffInput): Promise<ProofResult[]> {
  const gitTarget: { target: string } = input.proofInput.git ?? {
    target: input.settings.git.target,
  };
  const { strategies, git: _git, ...base } = input.proofInput;
  const proof = await generateProofs(
    { ...base, git: gitTarget },
    strategies,
    input.playwrightTuning,
  );
  await input.adapter.commentIssue(input.repo, input.issueIid, proofCommentBody(proof));
  return proof;
}

export async function proofAndHandoff(input: ProofAndHandoffInput): Promise<ProofResult[]> {
  const gitTarget: { target: string } = input.proofInput.git ?? {
    target: input.settings.git.target,
  };
  const { strategies, git: _git, ...base } = input.proofInput;
  const proof = await generateProofs(
    { ...base, git: gitTarget },
    strategies,
    input.playwrightTuning,
  );
  await handoff({
    repo: input.repo,
    issueIid: input.issueIid,
    mrIid: input.mrIid,
    ticketCreator: input.ticketCreator,
    settings: input.settings,
    adapter: input.adapter,
    proof,
  });
  return proof;
}
