// Handoff orchestration (spec §7). Turns an agent `done` into a review-ready,
// human-pinged MR via a FIXED ordered sequence over the M2 adapter surface:
//
//   proof comment (issue) → proof comment (MR) → assign reviewer → un-draft → label in-review
//
// The ordering is the contract (§7): the human is pinged (assignMR) ONLY after the
// proof is posted, so review-ready means everything is ready. Proof is generated by
// the caller and passed in (frozen HandoffInput.proof); `proofAndHandoff` composes
// generation + handoff and preserves "proof generated before reviewer assigned".
//
// Re-entrant on crash recovery (§0.4): each mutating step is guarded by an OBSERVABLE
// forge predicate read from a fresh snapshot, so a re-run skips already-applied steps
// — no double-comment, no double-assign, no local persistence. The DONE_SENTINEL
// embedded in the proof comment is the legible "proof already posted" marker.

import {
  DONE_SENTINEL,
  type HandoffInput,
  type IssueSnapshot,
  type ProofInput,
  type ProofResult,
} from '../contracts/index.js';
import { type PlaywrightTuning, generateProof } from '../proof/strategies.js';

function proofCommentBody(proof: ProofResult): string {
  const header = proof.ok ? '### ✅ Proof' : '### ⚠️ Proof (failed — review with caution)';
  return `${header}\n\n${proof.summary}\n\n${DONE_SENTINEL}`;
}

/**
 * Execute the §7 handoff sequence idempotently. Reads current forge state once, then
 * runs each step only if its predicate is unsatisfied. Matches the frozen HandoffFn.
 */
export async function handoff(input: HandoffInput): Promise<void> {
  const { adapter, repo, issueIid, mrIid, ticketCreator, settings, proof } = input;
  const snap = await adapter.getSnapshot(repo, issueIid);
  const mr = snap.mr;

  // 1+2. Proof comments (issue then MR) — guarded by the sentinel on the issue.
  const proofPosted = snap.recentComments.some((c) => c.body.includes(DONE_SENTINEL));
  if (!proofPosted) {
    const body = proofCommentBody(proof);
    await adapter.commentIssue(repo, issueIid, body);
    await adapter.commentMR(repo, mrIid, body);
  }

  // 3. Assign the ticket creator (the reviewer) — guarded by current assignees.
  const assigned = (mr?.assignees ?? []).some((a) => a.username === ticketCreator);
  if (!assigned) {
    await adapter.assignMR(repo, mrIid, ticketCreator);
  }

  // 4. Un-draft — guarded by draft state.
  if (mr?.isDraft !== false) {
    await adapter.setDraft(repo, mrIid, false);
  }

  // 5. Label in-review (terminal step) — guarded by label presence.
  const labeled = snap.issue.labels.includes(settings.labels.inReview);
  if (!labeled) {
    await adapter.setIssueLabels(
      repo,
      issueIid,
      [settings.labels.inReview],
      [settings.labels.inProgress],
    );
  }
}

/** Is the handoff fully complete per forge state? (Used by M5 to short-circuit.) */
export function isHandoffComplete(
  input: Pick<HandoffInput, 'settings'>,
  snapshot: IssueSnapshot,
): boolean {
  const mr = snapshot.mr;
  const proofPosted = snapshot.recentComments.some((c) => c.body.includes(DONE_SENTINEL));
  const labeled = snapshot.issue.labels.includes(input.settings.labels.inReview);
  return proofPosted && mr?.isDraft === false && labeled;
}

export interface ProofAndHandoffInput extends Omit<HandoffInput, 'proof'> {
  proofInput: Omit<ProofInput, 'git'> & { git?: { target: string } };
  playwrightTuning?: PlaywrightTuning;
}

/**
 * Compose generation + handoff: generate proof FIRST, then run the ordered handoff.
 * This is the unit M5 calls on `AgentResult.status === 'done'`. Proof generation
 * completing before any adapter mutation preserves the §7 proof-before-assign
 * guarantee end-to-end.
 */
export async function proofAndHandoff(input: ProofAndHandoffInput): Promise<ProofResult> {
  const gitTarget: { target: string } = input.proofInput.git ?? {
    target: input.settings.git.target,
  };
  const proof = await generateProof(
    { ...input.proofInput, git: gitTarget },
    input.playwrightTuning,
  );
  await handoff({
    repo: input.repo,
    issueIid: input.issueIid,
    mrIid: input.mrIid,
    ticketCreator: input.ticketCreator,
    settings: input.settings,
    adapter: input.adapter,
    proof,
  });
  return proof;
}
